### ISSUE TITLE
/proc/0 error on Linux

### ISSUE THREAD

**Issue by theothertomelliott** [yext/edward#96]
Reproducible by having a pidfile for a service that is no longer running. May be a result of a service dying or restarting without stopping services.

**Comment by theindexer** [comment]
Line 92 of command.go clears the state, which gets rid of the bogus process file.
Line 95 then attempts to make a new process.
Line 79 process_linux.go (NewProcess(pid int32)) calls os.Open on /proc/0 since c.Pid is 0, which causes the output seen "open /proc/0: no such file or directory"

Thus you have to run an edward command once for each ghost process until you've reset them all.

**Comment by theothertomelliott** [comment]
Fixed by returning nil when the pid is reset.
